[package]
name = "wye"
description = "Wye: a native Linux browser picker"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
tokio.workspace = true
toml.workspace = true
tracing-subscriber.workspace = true
wye-api.workspace = true
wye-core.workspace = true
wye-desktop.workspace = true
wye-service.workspace = true
zbus.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
